---
title: "iNaturalist Summary"
author: "Jeff Matheson"
format: html
project:
  type: website
  output-dir: docs
editor: visual
---

```{r}
#| message: FALSE
#| echo: FALSE

library(tidyverse)
library(kableExtra)
library(leaflet)

```

## Data

Downloaded from iNaturalist website on Dec 1. All records for Bowen Island.

```{r}
#| message: FALSE

inat <- read_csv("inat/observations-380595.csv")
```

Number of records: `r nrow(inat)`

**Column names:**

```{r}
names(inat) |> kable()
```

**Record grade by kingdom:**

```{r}
table(inat$taxon_kingdom_name, inat$quality_grade)
```

**Map all locations by Kingdom**

```{r}
pal.inat <- colorFactor(topo.colors(6), inat$taxon_kingdom_name)

leaflet(inat) |> 
  addTiles() |> 
  addCircleMarkers(lng = ~longitude, lat = ~latitude,
                   radius = 1,
                   popup = paste(inat$scientific_name, "<br>",
                               inat$taxon_kingdom_name),
                 color = ~pal.inat(taxon_kingdom_name),
                 group = "iNat Observations")
```
